version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - "db"
  db:
    image: mysql:5.7.15
    ports:
      - "8090:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: workyourlight
    volumes:
      - .docker-config:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data: