version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
      CODECOV_TOKEN: 35398d6d-004d-4f91-b278-b35a40a3e6f0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test
      - codecov/upload:
          conf: .codecov/.codecov.yml
          token: ${CODECOV_TOKEN}