version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
      CODECOV_TOKEN: 35398d6d-004d-4f91-b278-b35a40a3e6f0

    steps:
      - checkout
      - restore_cache:
          name: Restoring cache
          keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              - v1-dependencies-
      - run:
          name: Getting dependencies
          command: 'mvn dependency:go-offline'
      - save_cache:
          name: Saving cache dependencies
          paths:
              - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: 'mvn install -DskipITs'
      - run:
          name: IntegrationTest
          command: 'mvn failsafe:integration-test'
      - codecov/upload:
          conf: .codecov/.codecov.yml
          token: ${CODECOV_TOKEN}
      - store_artifacts:
          path: target/*.jar
  deploy:
      docker:
          - image: buildpack-deps:trusty
      environment:
          HEROKU_APP_NAME: oracle-reader
          HEROKU_API_KEY: cafafefb-6f49-41cc-b35b-e216db00ceab
      steps:
          - checkout
          - run:
              name: Deploy Develop to Heroku
              command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: develop